---
title: "Proposal"
author: "Wenxin Du, Gio Corti, Ilana Heaton"
date: "3/29/2018"
output: github_document
---

1. General theme: We want to look at geographic and seasonal patterns in SMS usage. To analyze these we hope to look at user rate in specific locations over time.

2. Relevant Stakeholders:
    + Mercy Corps - who collected and compiled the data through their Mongolia LTS-2 project. 

3. Specific questions: 
    + What does usage of the SMS service look like over time?
    + Which districts/provinces have the most/least "regular" users? (Where "regular" is defined as long-term use of the system)
    + What is the churn rate of the SMS project (annual percentage rate at which customers stop using the service)?
    + Is the increased usage observed during spring related to spring migration? How can we determine by tracking changes in reported area codes by each unique user?
    + Can we forecast usage for 2018?
    + What future areas of study would help further/better explain patterns in data usage?

4. Relevant Work:
    These works will help us understand what nomadic herding in Mongolia looks like, including, but not limited to, spring migration patterns, herding techniques, and general living conditions of nomadic herders. 
    + "Climate Change Studies in Mongolia: Progress Report." Institute of Meteorology and Hydrology Mongolia. http://sedac.ciesin.columbia.edu/aiacc/progress/AS06_July03.pdf
    + Marin, Andrei. (2010). "Riders Under Storms: Contributions of nomadic herders’ observations to analysing climate change in Mongolia." *Global Environmental Change* 20(1), 162-176. https://www.sciencedirect.com/science/article/pii/S0959378009000892
    + Férnandez-Giménez, María E. (2010). Sustaining the Steppes: A Geographical History of Pastoral Land Use in Mongolia. https://doi.org/10.1111/j.1931-0846.1999.tb00222.x

5. Data: 
    We have yet to get our hands on the actual data but we know it contains:
    + Phone number - The phone numbers will be changed to unique identifiers 
    + time and date of an SMS
    + User zip code
    + Type of message requested
    + Message received


   
6. Deliverables:
Report answering the questions we posed above. This will include spatial/spatio-temporal visualizations, and bar graphs of churn rate and usage per month. A scatter plot/graphic that tries to correlate usage and extreme weather events might also be possible. We plan to model usage for the upcoming year/season. If we have time, we want to build a shiny app which combines geographical SMS data with temporal/seasonal information.