---
title: "Churn Rate"
name: "Ilana Heaton"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)
```

# What's the system's churn rate?
```{r}
In <- read_csv("~/nomadic-herders/LTSdata/In.csv") 
In <- In %>%
  select(-X1)

first_use <- In %>%
  mutate(month = month(Date), year = year(Date)) %>%
  group_by(id) %>%
  arrange(month, year) %>%
  slice(1) %>%
  ungroup() %>%
  group_by(month, year) %>%
  summarise(n = n()) %>%
  arrange(year)

total_use <- In %>%
  mutate(month = month(Date), year = year(Date)) %>%
  group_by(month, year) %>%
  distinct(id, .keep_all = TRUE) %>%
  summarise(total = n()) %>%
  arrange(year)

left_join(first_use, total_use, by = c("year" = "year", "month" = "month")) %>%
  mutate(churn = n/total)
  

last_use <- In %>% 
  mutate(month = month(Date), year = year(Date)) %>%
  group_by(id) %>%
  arrange(month, year) %>%
  slice(n()) %>%
  ungroup() %>%
  group_by(month, year) %>%
  summarise(n = n()) %>%
  arrange(year)

left_join(last_use, total_use, by = c("year" = "year", "month" = "month")) %>%
  mutate(churn = n/total) %>% arrange(desc(churn))

left_join(last_use, total_use, by = c("year" = "year", "month" = "month")) %>%
  mutate(churn = n/total) %>%
  ungroup() %>%
  filter(!row_number() == n()) %>%
  mutate(date = make_date(year = year, month = month)) %>%
ggplot(aes(x = date, y = churn)) + geom_col() + labs(title = "Monthly Churn Rate June 2016- November 2017", y = "Rate", x = "month") + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(),  axis.line = element_line(colour = "black")) 

a <- date("2016-12-01")
b <- date("2016-06-01")
e <- date("2017-07-01")
d <- date("2017-10-01")

left_join(last_use, total_use, by = c("year" = "year", "month" = "month")) %>%
  mutate(churn = n/total) %>%
  ungroup() %>%
  filter(!row_number() == n()) %>%
  mutate(date = make_date(year = year, month = month)) %>%
ggplot(aes(x = date, y = churn)) + geom_line() + labs(title = "Monthly Churn Rate June 2016 - November 2017", y = "Rate", x = "Month") + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(),  axis.line = element_line(colour = "black")) + annotate("text", x = a, y = 1, label = c("December")) +
  annotate("text", x = b, y = 0.82, label = c("June")) + annotate("text", x = e, y = 0.33, label = c("July")) +
annotate("text", x = d, y = 0.62, label = c("November"))

  

```


