---
title: "Working with In/Outgoing messages"
name: "Ilana Heaton"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(rex)
library(readr)
library(readxl)
library(stringr)
library(lubridate)
```


```{r message = F}
# load deidentified data

LTS_data <- read_csv("~/nomadic-herders/LTSdata/LTS_deidentified (1).csv")

# wrangle data - get rid of unnecessary column

LTS_data <- LTS_data %>%
  select(-X1)

```

## Working with incoming messages
# Create incoming message dataframe with additional variables
```{r message = F}

# create incoming messages dataframe
In <- LTS_data %>%
  filter(Type == "in")

# regexpression to pull out messages in correct/incorrect format
correct_exp <- "^[0-9]{5}\\s+[0-9]{1}$"


# create correct/incorrect column
In$correct <- grepl(correct_exp,In$Message)


# create area column for correct/incorrect
In <- In %>%
  mutate(area = str_extract(In$Message, "[0-9]{5}")) 

# Is the area code correct?

zip_data <- read_excel("~/nomadic-herders/LTSdata/Zip_extension_2016_2017.xlsx") %>% rename(`Zip code` = `Regional code`)
zip_data2 <- read_excel("~/nomadic-herders/LTSdata/Zip_extension_2017_2018.xlsx") %>%
  select("Sub-District", "Zip code", "Latitude", "Longitude") 
 

Zip_Data <- bind_rows(zip_data, zip_data2) %>%
  distinct(`Zip code`)

area_vector <- as.vector(Zip_Data$`Zip code`)

In <- In %>%
  mutate(area_correct = if_else(In$area %in% area_vector, 'real', 'fake')) %>% mutate(area_correct = if_else(is.na(In$area), 'fake', area_correct))

In %>% filter(area_correct == "real") %>%
  summarise(n = n())

write.csv(In, file = "In.csv")

# separate message column into area code and request type - this probably only makes sense to do for correct messages
Correct <- In %>%
  filter(correct == "TRUE") %>%
  separate(Message, c("area", "request"), sep = ("(\\s{1,4}|\\.)"), extra = "drop")

write.csv(Correct, file = "Correct.csv")

```


## Working with outgoing messages

```{r message = F}
# outgoing messages - separate to translate

Out <- LTS_data %>%
  filter(Type == "out") 

# create a column for the type of outgoing message
weather_exp <- "((nartai)|(borootoi)|(tsastai)|(uulerheg))"

  
Out$info_type <- if_else(grepl(weather_exp, Out$Message),'weather','pasture')

Out <- Out %>%
  mutate(weather = str_extract(Out$Message, weather_exp))

# create weather key 
Weather <- tribble(
  ~weather_eng, ~weather_mon, 
  "snow ", "tsastai",
  "rain", "borootoi",
  "sun", "nartai",
  "clouds", "uulerheg")

#join english with mongolian weather forecast

Out <- Out %>%
  full_join(Weather, by = c("weather" = "weather_mon"))

write.csv(Out, "out_LTS_data.csv")
```